-- Habilitar extensión pgvector para el RAG
CREATE EXTENSION IF NOT EXISTS vector;

-- Tabla especialistas
CREATE TABLE specialists (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  specialty TEXT NOT NULL,
  schedule TEXT NOT NULL,
  photo TEXT NOT NULL
);

-- Tabla servicios
CREATE TABLE services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL
);

-- Tabla intermedia especialistas_servicios (Relación N a N)
CREATE TABLE specialist_services (
  specialist_id BIGINT REFERENCES specialists(id) ON DELETE CASCADE,
  service_id BIGINT REFERENCES services(id) ON DELETE CASCADE,
  PRIMARY KEY (specialist_id, service_id)
);

-- Tabla citas (appointments)
CREATE TABLE appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  specialist_id BIGINT REFERENCES specialists(id),
  appointment_date DATE NOT NULL,
  appointment_time TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  service_name TEXT NOT NULL,
  payment_method TEXT DEFAULT 'Efectivo' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla para conocimiento base (RAG)
CREATE TABLE knowledge_base (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  embedding vector(1536) -- asumiendo que se usará text-embedding-ada-002 o text-embedding-3-small de OpenAI
);

-- Insertar datos iniciales (Mocks actuales del frontend)
INSERT INTO specialists (name, specialty, schedule, photo) VALUES
('Valentina', 'Uñas y acrílicas', 'Lun–Sáb · 9am–5pm', 'https://i.pravatar.cc/200?img=1'),
('Isabella', 'Corte y coloración', 'Mar–Sáb · 10am–6pm', 'https://i.pravatar.cc/200?img=5'),
('Camila', 'Cejas y pestañas', 'Lun–Vie · 9am–4pm', 'https://i.pravatar.cc/200?img=9'),
('Daniela', 'Facial y masajes', 'Mié–Dom · 11am–7pm', 'https://i.pravatar.cc/200?img=10');

INSERT INTO services (name) VALUES
('Manicure'), ('Pedicure'), ('Uñas acrílicas'), ('Corte'), ('Coloración'), ('Cejas'), ('Pestañas'), ('Facial');

-- Relacionar especialistas con servicios
INSERT INTO specialist_services (specialist_id, service_id) VALUES
(1, 1), -- Valentina -> Manicure
(1, 2), -- Valentina -> Pedicure
(1, 3), -- Valentina -> Uñas acrílicas
(2, 4), -- Isabella -> Corte
(2, 5), -- Isabella -> Coloración
(3, 6), -- Camila -> Cejas
(3, 7), -- Camila -> Pestañas
(4, 8); -- Daniela -> Facial

-- ============================================================
-- SEGURIDAD (Row Level Security - RLS)
-- ============================================================

-- 1. Habilitar RLS en todas las tablas
ALTER TABLE specialists ENABLE ROW LEVEL SECURITY;
ALTER TABLE services ENABLE ROW LEVEL SECURITY;
ALTER TABLE specialist_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_base ENABLE ROW LEVEL SECURITY;

-- 2. Políticas para Specialists (Lectura pública para cargar la web)
CREATE POLICY "Permitir lectura pública de especialistas" 
ON specialists FOR SELECT 
TO anon, authenticated 
USING (true);

-- 3. Políticas para Services (Lectura pública para cargar la web)
CREATE POLICY "Permitir lectura pública de servicios" 
ON services FOR SELECT 
TO anon, authenticated 
USING (true);

-- 4. Políticas para specialist_services (Lectura pública de relaciones)
CREATE POLICY "Permitir lectura pública de relaciones" 
ON specialist_services FOR SELECT 
TO anon, authenticated 
USING (true);

-- 5. Políticas para Appointments (Cualquiera puede agendar una cita, pero nadie público puede leer datos de otros)
CREATE POLICY "Permitir inserción pública de citas" 
ON appointments FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Nota: La tabla 'knowledge_base' no tiene políticas públicas creadas. 
-- Esto significa que está 100% protegida y solo nuestro Backend (usando la service_role key) podrá consultarla.


-- ============================================================
-- FUNCIONES DE SEGURIDAD SECURE RPC
-- ============================================================

-- Función segura para consultar horas ocupadas sin exponer nombres, correos o teléfonos de clientes
CREATE OR REPLACE FUNCTION get_booked_times(p_specialist_id BIGINT, p_date DATE)
RETURNS TABLE (appointment_time TEXT) 
SECURITY DEFINER -- Ejecuta con permisos del creador, evadiendo RLS de forma segura
AS $$
BEGIN
  RETURN QUERY
  SELECT a.appointment_time 
  FROM appointments a
  WHERE a.specialist_id = p_specialist_id 
    AND a.appointment_date = p_date;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- MIGRACIÓN (EJECUTAR SI YA TIENES LA TABLA appointments CREADA)
-- ============================================================
-- Si no quieres borrar tus tablas y volver a crearlas desde cero, 
-- puedes agregar el nuevo campo de método de pago ejecutando esta línea en tu SQL Editor:
--
-- ALTER TABLE appointments ADD COLUMN payment_method TEXT DEFAULT 'Efectivo' NOT NULL;


